version: '3.8'

services:
  app:
    build: .
    container_name: expirapp-backend
    ports:
      - "8080:8080"
        environment:
          - DB_HOST=db
          - DB_PORT=5432
          - DB_USER=postgres
          - DB_PASSWORD=postgres
          - DB_NAME=expirapp
          - DB_SSLMODE=disable
          - DB_TIMEZONE=UTC
        volumes:
          - ./uploads:/root/uploads
        depends_on:
          - db
        restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: expirapp-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=expirapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/AS_BD.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data:
